#!bin/bash
clear
echo -e "$barra"
echo -e "\E[41;1;37mMULTI-SCRIPTS MANAGER             \033[1;32m[\033[1;37m VERSAO: r090 \033[1;32m]\E[0m"
echo -e "$barra"
echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;33mSSHPLUS MANAGER                \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;33mADM-MANAGER-ULTIMATE (ALPHA)   \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;33mNEW-ULTIMATE MANAGER           \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m04\033[1;31m] \033[1;33mVPS-MANAGER-V3.0               \033[1;32m(FREE) " 
echo -e "\033[1;31m[\033[1;36m05\033[1;31m] \033[1;33mVPSPACK-SERVER-V2.0            \033[1;32m(FREE) "
echo -e "\033[1;31m[\033[1;36m06\033[1;31m] \033[1;33mNEWADM MOD DANKELTHAHER        \033[1;32m(FREE) " 
echo -e "\033[1;31m[\033[1;36m07\033[1;31m] \033[1;33mVPSMX BY KALIX1 v8.3.1         \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m08\033[1;31m] \033[1;33mVPSMX BY KALIX1 v8.4           \033[1;32m(FREE) \033[37m∆ "
echo -e "$barra"
echo -e "\033[1;31m[\033[1;36m09\033[1;31m] \033[1;33mNEW ADM-VPS OFICIAL            \033[1;31m(KEYS) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m10\033[1;31m] \033[1;33mSSHPLUS MANAGER OFICIAL        \033[1;31m(KEYS) "
echo -e "\033[1;31m[\033[1;36m11\033[1;31m] \033[1;33mADM-MANAGER BY SCHUMOGH        \033[1;31m(KEYS) "
echo -e "\033[1;31m[\033[1;36m12\033[1;31m] \033[1;33mNEW-ULTIMATE OFICIAL-LIV       \033[1;32m(FREE) " 
echo -e "$barra"
echo -e "\033[1;31m[\033[1;36m13\033[1;31m] \033[1;33mVPSMX BY KALIX1-CASITA v8.1    \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m14\033[1;31m] \033[1;33mVPSPACK BY POWERMX-CASITA v5.8 \033[1;32m(FREE) " 
echo -e "\033[1;31m[\033[1;36m15\033[1;31m] \033[1;33mADMMX BY SIXREAPER-CASITA      \033[1;32m(FREE) \033[37m∆ "
echo -e "\033[1;31m[\033[1;36m16\033[1;31m] \033[1;33mSSHPLUS MANAGER ES-CASITA      \033[1;32m(FREE) "
echo -e "\033[1;31m[\033[1;36m17\033[1;31m] \033[1;33mNEWADM DANKELTHAHER-CASITA     \033[1;32m(FREE) \033[1;31mOFF "
echo -e "$barra"
echo -e "\033[1;31m[\033[1;36m18\033[1;31m] \033[1;33mGENERADOR KEY SSHPLUS MANAGER  \033[1;32m(FREE) " 
echo -e "\033[1;31m[\033[1;36m19\033[1;31m] \033[1;33mMULTI-INTALADOR SSHPLUS        \033[1;32m(FREE) " 
echo -e "\033[1;31m[\033[1;36m20\033[1;31m] \033[1;33mPAINEL SSHPLUS WEB (VERSIONES) \033[1;32m(FREE) "
echo -e "$barra"
echo -e "\033[1;31m[\033[1;36m21\033[1;31m] \033[1;35m[!] \033[1;32mACTUALIZAR                \033[1;31mRam:\033[1;37m $_usor "
echo -e "\033[1;31m[\033[1;36m22\033[1;31m] \033[1;35m[!] \033[1;31mDESINSTALAR \033[1;35m[\033[1;37m MSM \033[1;35m]       \033[1;31mNucleo:\033[1;37m $_usop "
echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37mSALIR \033[1;32m<\033[1;33m<\033[1;31m<                     \033[1;37m@admmanagerfree\033[0m \033[0m"
echo -e "$barra"
echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   sshplusfree
   exit;
   ;;
   2 | 02)
   clear
   admmanageralpha
   exit;
   ;;
   3 | 03)
   clear
   newultimate
   exit;
   ;;
   4 | 04)
   clear
   vpsmanager30
   exit;
   ;;
   5 | 05)
   clear
   vpspack20
   exit;
   ;;      
   6 | 06)
   clear
   dankel
   exit;
   ;;
   7 | 07)
   clear
   scriptmx_illuminati
   exit;
   ;;
   8 | 08)
   clear
   scriptmx_illuminatiUpdate
   exit;
   ;; 
   9 | 09)
   clear
   admvps
   exit;
   ;;
   10 | 10)
   clear
   sshpluskey
   exit;
   ;;     
   11)
   clear
   cgh
   exit;
   ;;     
   12)
   clear
   newfreeinstaldev
   exit;
   ;;
   13)
   clear
   scriptmx_casita
   exit;
   ;;
   14)
   clear
   power
   exit;
   ;;
   15)
   clear
   scriptadmmx_reapergamo
   exit;
   ;;
   16)
   clear
   sshpluscasitaES
   exit;
   ;;
   17)
   clear
   dankelcasita
   exit;
   ;;
   18)
   clear
   keygenplus
   exit;
   ;;
   19)
   clear
   multiinstallplus
   exit;
   ;;
   20)
   clear
   panelweversiones
   exit;
   ;;
   21)
   clear
   atualizar
   exit;
   ;;
   22)
   clear
   remove_multiscripts
   exit;
   ;;
   0 | 00)
echo -e "\033[1;31mSaindo...\033[0m"
sleep 2
clear
exit;
;;
*)
echo -e "\n\033[1;31mOpcao invalida !\033[0m"
esac
done
}
menu
#fim
