#!bin/bash
 echo -e "\033[1;31m———————————————————————————————————————————————————\033[1;37m"
echo -e "\033[1;32m              Woli Lopez "
echo -e "\033[1;31m———————————————————————————————————————————————————\033[1;37m"
echo -e "\033[1;37m      WEBSOCKET SSH USARA ssl y pay
echo -ne "Mi nombre es:"
read nombre
echo -ne "Mi edad es:"
read edad
echo -ne "Me gusta:"
read gusta
echo "Me llamo $nombre tengo $edad años y me gusta $gusta"
